// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IAuthorFields {
  /** Name */
  name: string;

  /** Picture */
  picture: Asset;
}

export interface IAuthor extends IAuthorFields {
  __typename: string;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'author';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ICtaFields {
  /** Title */
  title?: string | undefined;

  /** Link */
  link?: string | undefined;
}

/** A call to action button */

export interface ICta extends Entry<ICtaFields> {
  __typename: string;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'cta';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IImageCarouselFields {
  /** Title */
  title?: string | undefined;

  /** Image */
  imageCollection?: any;
}

/** Slice */

export interface IImageCarousel extends Entry<IImageCarouselFields> {
  __typename: string;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'imageCarousel';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface INavBarFields {
  /** Title */
  title: string;

  /** Nav Links */
  navLinks: INavLink[];
}

/** Just a bunch of Nav Links smooshed together */

export interface INavBar extends Entry<INavBarFields> {
  __typename: string;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'navBar';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface INavLinkFields {
  /** Link Name */
  linkName: string;

  /** Link URL */
  linkUrl: string;
}

/** A link that will be added to the navbar */

export interface INavLink extends Entry<INavLinkFields> {
  __typename: string;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'navLink';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IPostFields {
  /** Title */
  title: string;

  /** Slug */
  slug: string;

  /** Content */
  content: Document;

  /** Excerpt */
  excerpt: string;

  /** Cover Image */
  coverImage: Asset;

  /** Date */
  date: string;

  /** Author */
  author: IAuthor;
}

export interface IPost extends Entry<IPostFields> {
  __typename: string;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'post';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ITemplatePageFields {
  /** Title */
  title?: string | undefined;

  /** Slug */
  slug: string;

  /** Slice */
  slice: (
    | IAuthor
    | ICta
    | IImageCarousel
    | IPost
    | ITemplatePage
    | ITwoColumnPost
  )[];
}

/** Trying to recreate a custom template page with "slices" like in Prismic */

export interface ITemplatePage extends Entry<ITemplatePageFields> {
  __typename: string;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'templatePage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ITwoColumnPostFields {
  /** Title */
  title?: string | undefined;

  /** Image */
  image?: Asset | undefined;

  /** Left Column */
  leftColumn?: Document | undefined;

  /** Right Column */
  rightColumn?: Document | undefined;

  /** Author */
  author: IAuthorFields;
}

/** Slice */

export interface ITwoColumnPost extends Entry<ITwoColumnPostFields> {
  __typename: string;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'twoColumnPost';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE =
  | 'author'
  | 'cta'
  | 'imageCarousel'
  | 'navBar'
  | 'navLink'
  | 'post'
  | 'templatePage'
  | 'twoColumnPost';

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
