import { fetchPostsByAuthor } from '../queries/posts';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';

export default function Home(posts) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>{JSON.stringify(posts)}</main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps(ctx) {
  const { data } = await fetchPostsByAuthor('Connor');

  return {
    props: { posts: data },
  };
}
